#!/usr/bin/expect -f

#log_user 0
set timeout 20

# Prefix commands
set cmds {
    "show route 23.128.76.0/24 short match 19366"
    "show route 23.158.168.0/24 short match 19366"
    "show route 23.158.184.0/24 short match 19366"
    "show route 23.164.232.0/24 short match 19366"
    "show route 23.169.240.0/24 short match 19366"
    "show route 23.169.241.0/24 short match 19366"
    "show route 23.169.242.0/24 short match 19366"
    "show route 23.169.243.0/24 short match 19366"
    "show route 23.169.244.0/24 short match 19366"
    "show route 23.169.245.0/24 short match 19366"
    "show route 23.169.248.0/24 short match 19366"
    "show route 23.169.249.0/24 short match 19366"
    "show route 23.169.250.0/24 short match 19366"
    "show route 23.169.251.0/24 short match 19366"
    "show route 23.169.252.0/24 short match 19366"
    "show route 23.169.253.0/24 short match 19366"
    "show route 23.169.254.0/24 short match 19366"
    "show route 23.169.255.0/24 short match 19366"
    "show route 23.187.248.0/24 short match 19366"
    "show route 44.76.16.0/24 short match 19366"
    "show route 44.78.16.0/24 short match 19366"
    "show route 64.40.23.0/24 short match 19366"
}

# Output log file
log_file -noappend bgp-tools-output.txt

# Start SSH
spawn ssh -oStrictHostKeyChecking=no lg@bgp.tools

# Just sleep until the banner settles
sleep 5

# Send each command
foreach cmd $cmds {
    send "$cmd\r"
    sleep 3
}

# Exit with Ctrl-D
send "\004"
expect eof

